/*
 * eeprom_addresses.h
 *
 * Created: 06/06/2014 16:46:11
 *  Author: P.Kirkpatrick
 */ 


#ifndef EEPROM_ADDRESSES_H_
#define EEPROM_ADDRESSES_H_

// System Settings
#define EEPROM_STACK_CONFIG							0x0007
#define EEPROM_LCD_CONTRAST_SET						0x0008
#define EEPROM_LCD_CONTRAST							0x0009

// Timelapse Settings
#define EEPROM_TIMELAPSE_INTERVAL_HI				0x0020			
#define EEPROM_TIMELAPSE_INTERVAL_LO				0x0021
#define EEPROM_TIMELAPSE_INTERVAL_UNITS				0x0022
#define EEPROM_TIMELAPSE_COUNT_HI					0x0023
#define EEPROM_TIMELAPSE_COUNT_LO					0x0024
#define EEPROM_TIMELAPSE_COUNT_UNITS				0x0025
#define EEPROM_TIMELAPSE_STARTDELAY_HI				0x0026
#define EEPROM_TIMELAPSE_STARTDELAY_LO				0x0027
#define EEPROM_TIMELAPSE_STARTDELAY_UNITS			0x0028
#define EEPROM_TIMELAPSE_ACTIVE						0x0029


// Timewarp Settings
#define EEPROM_TIMEWARP_COUNT_HI					0x002A
#define EEPROM_TIMEWARP_COUNT_LO					0x002B
#define EEPROM_TIMEWARP_DURATION_HI					0x002C
#define EEPROM_TIMEWARP_DURATION_LO					0x002D
#define EEPROM_TIMEWARP_DURATION_UNITS				0x002E
#define EEPROM_TIMEWARP_FUNCTION					0x002F
#define EEPROM_TIMEWARP_DIRECTION					0x0030
#define EEPROM_TIMEWARP_WAIT_HI						0x0031
#define EEPROM_TIMEWARP_WAIT_LO						0x0032
#define EEPROM_TIMEWARP_WAIT_UNITS					0x0033

// Bulb Ramping
#define EEPROM_BULBRAMP_START_EXPOSURE				0x0034
#define EEPROM_BULBRAMP_END_EXPOSURE				0x0035
#define EEPROM_BULBRAMP_STARTDELAY_HI				0x0036
#define EEPROM_BULBRAMP_STARTDELAY_LO				0x0037
#define EEPROM_BULBRAMP_STARTDELAY_UNITS			0x0038
#define EEPROM_BULBRAMP_COUNT_HI					0x0039
#define EEPROM_BULBRAMP_COUNT_LO					0x003A
#define EEPROM_BULBRAMP_DURATION_HI					0x003B
#define EEPROM_BULBRAMP_DURATION_LO					0x003C
#define EEPROM_BULBRAMP_DURATION_UNITS				0x003D

// Star Trail
#define EEPROM_STARTTRAIL_INTERVAL_HI				0x003E
#define EEPROM_STARTTRAIL_INTERVAL_LO				0x003F
#define EEPROM_STARTTRAIL_INTERVAL_UNITS			0x0040
#define EEPROM_STARTTRAIL_SHUTTERSPEED_HI			0x0041
#define EEPROM_STARTTRAIL_SHUTTERSPEED_LO			0x0042
#define EEPROM_STARTTRAIL_SHUTTERSPEED_UNITS		0x0043
#define EEPROM_STARTTRAIL_COUNT_HI					0x0044
#define EEPROM_STARTTRAIL_COUNT_LO					0x0045
#define EEPROM_STARTTRAIL_WAIT_HI					0x0046
#define EEPROM_STARTTRAIL_WAIT_LO					0x0047
#define EEPROM_STARTTRAIL_WAIT_UNITS				0x0048

// High Speed Flash
#define EEPROM_HSF_TRIGGERON						0x0049
#define EEPROM_HSF_CLOSESHUTTER						0x004A
#define EEPROM_HSF_SHUTTERCYCLE_HI					0x004B
#define EEPROM_HSF_SHUTTERCYCLE_LO					0x004C
#define EEPROM_HSF_SHUTTERCYCLE_UNITS				0x004D
#define EEPROM_HSF_FLASHDELAY_HI					0x004E
#define EEPROM_HSF_FLASHDELAY_LO					0x004F
#define EEPROM_HSF_FLASHDELAY_UNITS					0x0050
#define EEPROM_HSF_RESETDELAY_HI					0x0051
#define EEPROM_HSF_RESETDELAY_LO					0x0052
#define EEPROM_HSF_RESETDELAY_UNITS					0x0053
#define EEPROM_HSF_TIMESACTIVE						0x0054

#define EEPROM_HSF_START_HOURS						0x0089
#define EEPROM_HSF_START_MINS						0x008A
#define EEPROM_HSF_END_HOURS						0x008B
#define EEPROM_HSF_END_MINS							0x008C

// Sensor
#define EEPROM_SENSOR_TRIGDELAY_HI					0x0055
#define EEPROM_SENSOR_TRIGDELAY_LO					0x0056
#define EEPROM_SENSOR_TRIGDELAY_UNITS				0x0057
#define EEPROM_SENSOR_TRIGGERON						0x0058
#define EEPROM_SENSOR_MOBILEIP						0x0059
#define EEPROM_SENSOR_MOBILEOP						0x005A
#define EEPROM_SENSOR_TIMESACTIVE					0x005B

// Sensor Timelapse
#define EEPROM_SENSORTLAPSE_DELAY_HI				0x005C
#define EEPROM_SENSORTLAPSE_DELAY_LO				0x005D
#define EEPROM_SENSORTLAPSE_DELAY_UNITS				0x005E
#define EEPROM_SENSORTLAPSE_INTERVAL_HI				0x005F
#define EEPROM_SENSORTLAPSE_INTERVAL_LO				0x0060
#define EEPROM_SENSORTLAPSE_INTERVAL_UNITS			0x0061
#define EEPROM_SENSORTLAPSE_CONTINUE_HI				0x0062
#define EEPROM_SENSORTLAPSE_CONTINUE_LO				0x0063
#define EEPROM_SENSORTLAPSE_TRIGGERON				0x0064
#define EEPROM_SENSORTLAPSE_MOBILEIP				0x0065
#define EEPROM_SENSORTLAPSE_MOBILEOP				0x0066
#define EEPROM_SENSORTLAPSE_TIMESACTIVE				0x0067

// Sensor Video
#define EEPROM_SENSORVIDEO_DELAY_HI					0x0068
#define EEPROM_SENSORVIDEO_DELAY_LO					0x0069
#define EEPROM_SENSORVIDEO_DELAY_UNITS				0x006A
#define EEPROM_SENSORVIDEO_STOPAFTER_HI				0x006B
#define EEPROM_SENSORVIDEO_STOPAFTER_LO				0x006C
#define EEPROM_SENSORVIDEO_STOPAFTER_UNITS			0x006D
#define EEPROM_SENSORVIDEO_TRIGGER					0x006E
#define EEPROM_SENSORVIDEO_TIMESACTIVE				0x006F
#define EEPROM_SENSORVIDEO_TRIGGERON				0x0070

// Advanced Sensor
#define EEPROM_ADVSENSOR_CHAN1A						0x0071
#define EEPROM_ADVSENSOR_CHAN1B						0x0072
#define EEPROM_ADVSENSOR_CHAN2A						0x0073
#define EEPROM_ADVSENSOR_CHAN2B						0x0074
#define EEPROM_ADVSENSOR_CHAN3A						0x0075
#define EEPROM_ADVSENSOR_CHAN3B						0x0076
#define EEPROM_ADVSENSOR_TRIGMOBILE					0x0077

// Settings
#define EEPROM_CAMERAPREFOCUS_HI					0x0078
#define EEPROM_CAMERAPREFOCUS_LO					0x0079
#define EEPROM_CAMERAPREFOCUS_UNITS					0x007A
#define EEPROM_FLASHPULSE_HI						0x007B
#define EEPROM_FLASHPULSE_LO						0x007C
#define EEPROM_FLASHPULSE_UNITS						0x007D
#define EEPROM_SHUTTERPULSE_HI						0x007E
#define EEPROM_SHUTTERPULSE_LO						0x007F
#define EEPROM_SHUTTERPULSE_UNITS					0x0080

#define EEPROM_TIMELAPSE_STARTHOURS					0x0081
#define EEPROM_TIMELAPSE_STARTMINS					0x0082
#define EEPROM_TIMELAPSE_ENDHOURS					0x0083
#define EEPROM_TIMELAPSE_ENDMINS					0x0084

														
#define EEPROM_SENSORVIDEO_START_HOURS				0x008D
#define EEPROM_SENSORVIDEO_START_MINS				0x008E
#define EEPROM_SENSORVIDEO_END_HOURS				0x0090
#define EEPROM_SENSORVIDEO_END_MINS					0x0091

//LE_HDR
#define EEPROM_LEHDR_MID_EXP						0x0092
#define EEPROM_LEHDR_SHOTS							0x0093
#define EEPROM_LEHDR_EVPERSHOT						0x0094
#define EEPROM_LEHDR_TIMELAPSE_HI					0x0095
#define EEPROM_LEHDR_TIMELAPSE_LO					0x0096
#define EEPROM_LEHDR_TIMELAPSE_UNITS				0x0097

#define EEPROM_SENSOR_TL_START_HOURS				0x00AB
#define EEPROM_SENSOR_TL_START_MINS					0x00AC
#define EEPROM_SENSOR_TL_END_HOURS					0x00AD
#define EEPROM_SENSOR_TL_END_MINS					0x00AE
#define EEPROM_SENSORTLAPSE_CONTINUE				0x00AF

#define EEPROM_SENSOR_REST_DELAY_HI					0x00B0
#define EEPROM_SENSOR_REST_DELAY_LO					0x00B1
#define EEPROM_SENSOR_RESET_UNITS					0x00B2
#define EEPROM_SENSOR_START_HOURS					0x00B3
#define EEPROM_SENSOR_START_MINS					0x00B4
#define EEPROM_SENSOR_END_HOURS						0x00B5
#define EEPROM_SENSOR_END_MINS						0x00B6

// Advanced Sensor
#define EEPROM_ADVSENSOR_CHAN1A_DELAY_HI			0x00B7
#define EEPROM_ADVSENSOR_CHAN1A_DELAY_LO			0x00B8
#define EEPROM_ADVSENSOR_CHAN1A_DELAY_UNITS			0x00B9

#define EEPROM_ADVSENSOR_CHAN1B_DELAY_HI			0x00BA
#define EEPROM_ADVSENSOR_CHAN1B_DELAY_LO			0x00BB
#define EEPROM_ADVSENSOR_CHAN1B_DELAY_UNITS			0x00BC

#define EEPROM_ADVSENSOR_CHAN2A_DELAY_HI			0x00BD
#define EEPROM_ADVSENSOR_CHAN2A_DELAY_LO			0x00BE
#define EEPROM_ADVSENSOR_CHAN2A_DELAY_UNITS			0x00BF

#define EEPROM_ADVSENSOR_CHAN2B_DELAY_HI			0x00C0
#define EEPROM_ADVSENSOR_CHAN2B_DELAY_LO			0x00C1
#define EEPROM_ADVSENSOR_CHAN2B_DELAY_UNITS			0x00C2

#define EEPROM_ADVSENSOR_CHAN3A_DELAY_HI			0x00C3
#define EEPROM_ADVSENSOR_CHAN3A_DELAY_LO			0x00C4
#define EEPROM_ADVSENSOR_CHAN3A_DELAY_UNITS			0x00C5

#define EEPROM_ADVSENSOR_CHAN3B_DELAY_HI			0x00C6
#define EEPROM_ADVSENSOR_CHAN3B_DELAY_LO			0x00C7
#define EEPROM_ADVSENSOR_CHAN3B_DELAY_UNITS			0x00C8

//pulse duration
#define EEPROM_ADVSENSOR_CHAN1A_PULSE_HI			0x00C9
#define EEPROM_ADVSENSOR_CHAN1A_PULSE_LO			0x00CA
#define EEPROM_ADVSENSOR_CHAN1A_PULSE_UNITS			0x00CB

#define EEPROM_ADVSENSOR_CHAN1B_PULSE_HI			0x00CC
#define EEPROM_ADVSENSOR_CHAN1B_PULSE_LO			0x00CD
#define EEPROM_ADVSENSOR_CHAN1B_PULSE_UNITS			0x00CE

#define EEPROM_ADVSENSOR_CHAN2A_PULSE_HI			0x00CF
#define EEPROM_ADVSENSOR_CHAN2A_PULSE_LO			0x00D0
#define EEPROM_ADVSENSOR_CHAN2A_PULSE_UNITS			0x00D1

#define EEPROM_ADVSENSOR_CHAN2B_PULSE_HI			0x00D2
#define EEPROM_ADVSENSOR_CHAN2B_PULSE_LO			0x00D3
#define EEPROM_ADVSENSOR_CHAN2B_PULSE_UNITS			0x00D4

#define EEPROM_ADVSENSOR_CHAN3A_PULSE_HI			0x00D5
#define EEPROM_ADVSENSOR_CHAN3A_PULSE_LO			0x00D6
#define EEPROM_ADVSENSOR_CHAN3A_PULSE_UNITS			0x00D7

#define EEPROM_ADVSENSOR_CHAN3B_PULSE_HI			0x00D8
#define EEPROM_ADVSENSOR_CHAN3B_PULSE_LO			0x00D9
#define EEPROM_ADVSENSOR_CHAN3B_PULSE_UNITS			0x00DA

#define EEPROM_ADVSENSOR_REST_DELAY_HI				0x00DC
#define EEPROM_ADVSENSOR_REST_DELAY_LO				0x00DD
#define EEPROM_ADVSENSOR_REST_DELAY_UNITS			0x00DE
#define EEPROM_ADVSENSOR_TRIGGER_ON					0x00DF

// Now obsolete - do not use
#define EEPROM_TIME_HOURS							0x00E0
#define EEPROM_TIME_MINS							0x00E1
#define EEPROM_TIME_SECS							0x00E2

#ifdef INCLUDE_NEWMODE
#define EEPROM_NEWMODE_TRIGGERON					0x00E3
#define EEPROM_NEWMODE_DELAY_HI						0x00E4
#define EEPROM_NEWMODE_DELAY_LO						0x00E5
#define EEPROM_NEWMODE_DELAY_UNITS					0x00E6
#endif

#define EEPROM_NONE									0xFFFFU


#endif /* EEPROM_ADDRESSES_H_ */