#ifndef GUIMENU_PAGES_H_
#define GUIMENU_PAGES_H_




// Page IDs
#define GUIMENU_START_PAGE							0
#define GUIMENU_TIMELAPSE_TITLE_PAGE				1
#define GUIMENU_TIMEWARP_TITLE_PAGE					2
#define GUIMENU_BULBRAMPING_TITLE_PAGE				3
#define GUIMENU_STARTRAIL_TITLE_PAGE				4
#define GUIMENU_HISPEEDFLASH_TITLE_PAGE				5
#define GUIMENU_SENSOR_TITLE_PAGE					6
#define GUIMENU_SENSORTLAPSE_TITLE_PAGE				7
#define GUIMENU_SENSORTVIDEO_TITLE_PAGE				8
#define GUIMENU_ADVSENSOR_TITLE_PAGE				9
#define GUIMENU_LEHDR_TITLE_PAGE					10
#define GUIMENU_TIMELAPSE_START_PAGE				11
#define GUIMENU_TIMELAPSE_COUNT_PAGE				12
#define GUIMENU_TIMELAPSE_STOP_PAGE					13
#define GUIMENU_BULBRAMP_START_PAGE					14
#define GUIMENU_BULBRAMP_COUNT_PAGE					15
#define GUIMENU_BULBRAMP_STOP_PAGE					16
#define GUIMENU_TIMEWARP_START_PAGE					17
#define GUIMENU_TIMEWARP_FUNCTION_PAGE				18
#define GUIMENU_TIMEWARP_STOP_PAGE					19
#define GUIMENU_SENSORVIDEO_START_PAGE				20
#define GUIMENU_SENSORVIDEO_DELAY_PAGE				21
#define GUIMENU_POWEROFF_TITLE_PAGE					22
#define GUIMENU_SETTINGS_TITLE_PAGE					23
#define GUIMENU_CAMERA_PREFOCUS_PAGE				24
#define GUIMENU_SHUTTER_PULSE_PAGE					25
#define GUIMENU_FLASH_PULSE_PAGE					26
#define GUIMENU_HSF_START_PAGE						27
#define GUIMENU_HSF_STOP_PAGE						28
#define GUIMENU_HSF_TRIGGERON_PAGE					29
#define GUIMENU_SENTLAPSE_START_PAGE				30
#define GUIMENU_SENTLAPSE_PROG_PAGE					31
#define GUIMENU_TIMELAPSE_INTERVAL_PAGE				32
#define GUIMENU_TIMELAPSE_START_DELAY_PAGE			33
#define GUIMENU_TIMEWARP_COUNT_PAGE					34
#define GUIMENU_TIMEWARP_DIRECTION_PAGE				35
#define GUIMENU_TIMEWARP_WAIT_PAGE					36
#define GUIMENU_TIMEWARP_DURATION_PAGE				37
#define GUIMENU_BULBRAMP_END_EXPOSURE_PAGE			38
#define GUIMENU_BULBRAMP_STARTDELAY_PAGE			39
#define GUIMENU_BULBRAMP_DURATION_PAGE				40
#define GUIMENU_HSF_CLOSE_SHUTTER_PAGE				41
#define GUIMENU_HSF_SHUTTER_CYCLING_PAGE			42
#define GUIMENU_HSF_FLASH_DELAY_PAGE				43
#define	GUIMENU_HSF_RESET_DELAY_PAGE				44
#define GUIMENU_HSF_TIMESACTIVE_PAGE				45
#define GUIMENU_HSF_STARTTIME_PAGE					46
#define GUIMENU_HSF_ENDTIME_PAGE					47
#define GUIMENU_SENSORVIDEO_STOP_ACT_PAGE			48
#define GUIMENU_SENSORVIDEO_TRIGGER_PAGE			49
#define GUIMENU_SENSORVIDEO_TIMESACTIVE_PAGE		50
#define GUIMENU_SENSORVIDEO_STARTTIME_PAGE			51
#define GUIMENU_SENSORVIDEO_ENDTIME_PAGE			52
#define GUIMENU_SENSORVIDEO_TRIGGERON_PAGE			53												
#define GUIMENU_TIMELAPSE_TIMESACTIVE_PAGE			54
#define GUIMENU_TIMELAPSE_STARTTIME_PAGE			55
#define GUIMENU_TIMELAPSE_ENDTIME_PAGE				56
#define GUIMENU_SETTINGS_SETSYSTEM_TIME_PAGE		57
#define GUIMENU_STARTRAIL_START_PAGE				58
#define GUIMENU_STARTRAIL_INTERVAL_PAGE				59
#define GUIMENU_STARTRAIL_SHUTTER_SPEED_PAGE		60
#define GUIMENU_STARTRAIL_COUNT_PAGE				61
#define GUIMENU_STARTRAIL_DELAY_PAGE				62
#define GUIMENU_STARTRAIL_STOP_PAGE					63
#define GUIMENU_BULBRAMP_START_EXPOSURE_PAGE		64												
#define GUIMENU_LEHDR_MID_EXP_PAGE					65
#define GUIMENU_LEHDR_SHOTS_PAGE					66
#define GUIMENU_LEHDR_EV_PER_STEP_PAGE				67
#define GUIMENU_LEHDR_TIMELAPSE_PAGE				68
#define GUIMENU_LEHDR_START_PAGE					69
#define GUIMENU_LEHDR_STOP_PAGE						70
#define GUIMENU_SENSOR_START_PAGE					71
#define GUIMENU_SENSOR_STOP_PAGE					72
#define GUIMENU_SENSOR_TRIGGER_DELAY_PAGE			73
#define GUIMENU_SENSOR_RESET_DELAY_PAGE				74
#define GUIMENU_SENSOR_TIRGGER_ON_PAGE				75
#define GUIMENU_SENSOR_MOBILE_INPUT_PAGE			76
#define GUIMENU_SENSOR_MOBILE_OUTPUT_PAGE			77
#define GUIMENU_SENSOR_TIME_ACTIVE_PAGE				78
#define GUIMENU_SENSOR_START_TIME_PAGE				79
#define GUIMENU_SENSOR_STOP_TIME_PAGE				80
#define GUIMENU_SENSOR_TL_START_PAGE				81
#define GUIMENU_SENSOR_TL_STOP_PAGE					82
#define GUIMENU_SENSOR_TL_DELAY_PAGE				83
#define GUIMENU_SENSOR_TL_INTERVAL_PAGE				84
#define GUIMENU_SENSOR_TL_CONTINUE_PAGE				85
#define GUIMENU_SENSOR_TL_TRIGGER_ON_PAGE			86
#define GUIMENU_SENSOR_TL_MOBILE_INPUT_PAGE			87
#define GUIMENU_SENSOR_TL_MOBILE_OUTPUT_PAGE		88
#define GUIMENU_SENSOR_TL_TIME_ACTIVE_PAGE			89
#define GUIMENU_SENSOR_TL_START_TIME_PAGE			90
#define GUIMENU_SENSOR_TL_STOP_TIME_PAGE			91
#define GUIMENU_SENSOR_TL_CONTINUE_SET_PAGE			92
#define GUIMENU_A_SENSOR_START_PAGE					93
#define GUIMENU_A_SENSOR_STOP_PAGE					94
#define GUIMENU_A_SENSOR_CH1A_DELAY_PAGE			95
#define GUIMENU_A_SENSOR_CH1A_PULSE_PAGE			96
#define GUIMENU_A_SENSOR_CH1B_DELAY_PAGE			97
#define GUIMENU_A_SENSOR_CH1B_PULSE_PAGE			98
#define GUIMENU_A_SENSOR_CH2A_DELAY_PAGE			99
#define GUIMENU_A_SENSOR_CH2A_PULSE_PAGE			100
#define GUIMENU_A_SENSOR_CH2B_DELAY_PAGE			101
#define GUIMENU_A_SENSOR_CH2B_PULSE_PAGE			102
#define GUIMENU_A_SENSOR_CH3A_DELAY_PAGE			103
#define GUIMENU_A_SENSOR_CH3A_PULSE_PAGE			104
#define GUIMENU_A_SENSOR_CH3B_DELAY_PAGE			105
#define GUIMENU_A_SENSOR_CH3B_PULSE_PAGE			106
#define GUIMENU_A_SENSOR_TRIGGER_MOBILE_PAGE		107
#define GUIMENU_A_SENSOR_RESET_DELAY_PAGE			108
#define GUIMENU_A_SENSOR_TRIGGER_ON_PAGE			109
#define GUIMENU_SENSOR_VIDEO_STOP_PAGE				110
#define GUIMENU_LEHDR_PROG_PAGE						111
#define GUIMENU_TIMELAPSE_PROG_PAGE					112
#define GUIMENU_BRAMP_PROG_PAGE						113
#define GUIMENU_BRAMP_EXPOPROG_PAGE					114
#define GUIMENU_SETTINGS_ABOUT_PAGE					115
#define GUIMENU_HSF_CONFIG_PAGE						116
#define GUIMENU_SENSOR_CONFIG_PAGE					117
#define GUIMENU_SENSORTLAPSE_CONFIG_PAGE			118
#define GUIMENU_SENSORVIDEO_CONFIG_PAGE				119
#define GUIMENU_ADVSENSOR_CONFIG_PAGE				120
#define GUIMENU_STARTRAIL_PROG_PAGE					121
#define GUIMENU_TIMEWARP_PROG_PAGE					122


#ifdef INCLUDE_NEWMODE								
#define GUIMENU_NEWMODE_TITLE_PAGE					123			// Page used in the main menu
#define GUIMENU_NEWMODE_START_PAGE					124			// The first page in NewMode, from which control of the mode can be acheived
#define GUIMENU_NEWMODE_SETTLING_PAGE				125			// Shows the sensor settling progress bar
#define GUIMENU_NEWMODE_RUNNING_PAGE				126			// Displayed whilst the mode is in progress
#define GUIMENU_NEWMODE_TRIGGERON_PAGE				127			// Trigger On Setting Page
#define GUIMENU_NEWMODE_DELAY_PAGE					128			// Delay Setting Page
#define GUIMENU_NEWMODE_PROG_PAGE					129			// Progress bar Page for the delay
#endif

#define GUIMENU_NO_PAGE								255

#endif /* GUIMENU_PAGES_H_ */