#ifndef TT_STRINGS_H_
#define TT_STRINGS_H_

#define GUIMENU_NULL_STRING							0
#define GUIMENU_COUNT_TEXT							1
#define GUIMENU_IS									2
#define GUIMENU_TIMEWARP_SELECTOR_TEXT1				3
#define GUIMENU_SETUP								4
#define GUIMENU_TIMEWARP_FN1						5
#define GUIMENU_TIMEWARP_FN2						6
#define GUIMENU_TIMEWARP_FN3						7
#define GUIMENU_CANCEL								8
#define GUIMENU_DONE								9
#define GUIMENU_CAMERA_PREFOCUS_TEXT1				10
#define GUIMENU_CAMERA_PREFOCUS_TEXT2				11
#define GUIMENU_SHUTTER_TEXT						12
#define GUIMENU_PULSE_TEXT2							13
#define GUIMENU_FLASH_PULSE_TEXT1					14
#define GUIMENU_TRIGGER_ON_TEXT1					15
#define GUIMENU_TRIGGER_ON_TEXT2					16
#define GUIMENU_ALL_TEXT							17
#define GUIMENU_ANY_TEXT							18
#define GUIMENU_CLOSE_SHUTTER_TEXT1					19
#define GUIMENU_CLOSE_SHUTTER_TEXT2					20
#define GUIMENU_NO_TEXT								21
#define GUIMENU_YES_TEXT							22
#define GUIMENU_OPEN_TEXT							23
#define GUIMENU_ONE									24
#define GUIMENU_TIMELAPSE							25
#define GUIMENU_TWO									26
#define GUIMENU_TIMEWARP							27
#define GUIMENU_THREE								28
#define GUIMENU_BULB								29
#define GUIMENU_RAMPING								30
#define GUIMENU_FOUR								31
#define GUIMENU_STAR								32
#define GUIMENU_TRAIL								33
#define GUIMENU_FIVE								34
#define GUIMENU_HIGHSPEED							35
#define GUIMENU_FLASH								36
#define GUIMENU_SIX									37
#define GUIMENU_SENSOR								38
#define GUIMENU_SEVEN								39
#define GUIMENU_EIGHT								40
#define GUIMENU_VIDEO								41
#define GUIMENU_NINE								42
#define GUIMENU_ADVANCED							43
#define GUIMENU_TEN									44
#define GUIMENU_LEHDR								45
#define GUIMENU_START								46
#define GUIMENU_STOP								47
#define GUIMENU_POWEROFF							48
#define GUIMENU_SETTINGS							49
#define GUIMENU_MORE_SETTINGS						50
#define GUIMENU_SENSOR_TIMELAPSE					51
#define GUIMENU_INTERVAL							52
#define GUIMENU_STARTDELAY							53
#define GUIMENU_DIRECTION							54
#define GUIMENU_WAITBEFORE							55
#define GUIMENU_STARTIS								56
#define GUIMENU_DURATION							57
#define GUIMENU_EXPOSUREIS							58
#define GUIMENU_1D15								59
#define GUIMENU_1D13								60
#define GUIMENU_1D10								61
#define GUIMENU_1D8									62
#define GUIMENU_1D6									63
#define GUIMENU_1D5									64
#define GUIMENU_1D4									65
#define GUIMENU_0_3									66
#define GUIMENU_0_4									67
#define GUIMENU_0_5									68
#define GUIMENU_0_6									69
#define GUIMENU_0_8									70
#define GUIMENU_1_0									71
#define GUIMENU_1_3									72
#define GUIMENU_1_6									73
#define GUIMENU_2_0									74
#define GUIMENU_2_5									75
#define GUIMENU_3_2									76
#define GUIMENU_4_0									77
#define GUIMENU_5_0									78
#define GUIMENU_6_0									79
#define GUIMENU_8_0									80
#define GUIMENU_10_0								81
#define GUIMENU_13_0								82
#define GUIMENU_15_0								83
#define GUIMENU_20_0								84
#define GUIMENU_25_0								85
#define GUIMENU_30_0								86
#define GUIMENU_IN									87
#define GUIMENU_OUT									88
#define GUIMENU_INOUT								89
#define GUIMENU_OUTIN								90
#define GUIMENU_SYSTEMTIME							91
#define GUIMENU_BRAMPING							92
#define GUIMENU_END									93
#define GUIMENU_NO									94
#define GUIMENU_SETTING								95
#define GUIMENU_SHUTTER								96
#define GUIMENU_CYCLING								97
#define GUIMENU_DELAY								98
#define GUIMENU_RESET								99
#define GUIMENU_ACTIVE								100
#define GUIMENU_ALWAYS								101
#define GUIMENU_TIME								102
#define GUIMENU_TIMES								103
#define GUIMENU_SENSORVIDEO							104
#define GUIMENU_STOPAFTER							105
#define GUIMENU_ACTIVTY								106
#define GUIMENU_CAMERA								107
#define	GUIMENU_MOBILE								108
#define GUIMENU_BOTH								109
#define GUIMENU_TRIGGER								110
#define GUIMENU_SET									111
#define GUIMENU_STARTRAIL							112
#define GUIMENU_SPEED								113
#define GUIMENU_MIDDLE								114
#define GUIMENU_ELEVEN								115
#define GUIMENU_THIRTEEN							116
#define GUIMENU_FIFTEEN								117
#define GUIMENU_THIRD								118
#define GUIMENU_HALF								119
#define GUIMENU_EVPER								120
#define GUIMENU_SHOT								121
#define GUIMENU_SHOTS								122
#define GUIMENU_TRIGGER_DELAY						123
#define GUIMENU_RESET_DELAY							124
#define GUIMENU_TRIGGER_ON							125
#define GUIMENU_TIMES_ACTIVE						126
#define GUIMENU_OFF									127
#define GUIMENU_INPUT								128
#define GUIMENU_OUTPUT								129
#define GUIMENU_SENSOR_TL							130
#define GUIMENU_CONTINUE							131
#define GUIMENU_SENSOR_STOP							132
#define GUIMENU_INFINITE							133
#define GUIMENU_X_SHOTS								134		
#define GUIMENU_1A									135
#define GUIMENU_1B									136
#define GUIMENU_2A									137
#define GUIMENU_2B									138
#define GUIMENU_3A									139
#define GUIMENU_3B									140
#define GUIMENU_PULSE_DURATION						141
#define GUIMENU_A_SENSOR							142
#define GUIMENU_EXPO								143
#define GUIMENU_VERSION_NUM							144
#define GUIMENU_VERSION								145
#define GUIMENU_SETTINGS1							146
#define GUIMENU_MENUBACK							147
#define GUIMENU_LOW									148
#define GUIMENU_BATTERY								149

#ifdef INCLUDE_NEWMODE
#define GUIMENU_NEWMODE								150
#define GUIMENU_ON									151
#endif


#endif /* TT_STRINGS_H_ */